# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(67, 50, 661, 401))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.mainLayout.setContentsMargins(0, 10, 0, 10)
        self.mainLayout.setObjectName("mainLayout")
        self.layout_loadMemo = QtWidgets.QVBoxLayout()
        self.layout_loadMemo.setObjectName("layout_loadMemo")
        self.label_loadPaperInstruction = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_loadPaperInstruction.setObjectName("label_loadPaperInstruction")
        self.layout_loadMemo.addWidget(self.label_loadPaperInstruction)
        self.label_pastPaperFileName = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_pastPaperFileName.setObjectName("label_pastPaperFileName")
        self.layout_loadMemo.addWidget(self.label_pastPaperFileName)
        self.btn_loadPastPaper = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_loadPastPaper.setObjectName("btn_loadPastPaper")
        self.layout_loadMemo.addWidget(self.btn_loadPastPaper)
        self.mainLayout.addLayout(self.layout_loadMemo)
        self.layout_loadPastPaper = QtWidgets.QVBoxLayout()
        self.layout_loadPastPaper.setContentsMargins(-1, 10, -1, -1)
        self.layout_loadPastPaper.setObjectName("layout_loadPastPaper")
        self.label_loadMemoInstruction = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_loadMemoInstruction.setObjectName("label_loadMemoInstruction")
        self.layout_loadPastPaper.addWidget(self.label_loadMemoInstruction)
        self.label_memoFileName = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_memoFileName.setObjectName("label_memoFileName")
        self.layout_loadPastPaper.addWidget(self.label_memoFileName)
        self.btn_loadMemo = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_loadMemo.setObjectName("btn_loadMemo")
        self.layout_loadPastPaper.addWidget(self.btn_loadMemo)
        self.mainLayout.addLayout(self.layout_loadPastPaper)
        self.layout_generateLayout = QtWidgets.QVBoxLayout()
        self.layout_generateLayout.setContentsMargins(-1, 10, -1, -1)
        self.layout_generateLayout.setObjectName("layout_generateLayout")
        self.label_generateInstruction = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_generateInstruction.setObjectName("label_generateInstruction")
        self.layout_generateLayout.addWidget(self.label_generateInstruction)
        self.btn_generateLayout = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_generateLayout.setObjectName("btn_generateLayout")
        self.layout_generateLayout.addWidget(self.btn_generateLayout)
        self.mainLayout.addLayout(self.layout_generateLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_loadPaperInstruction.setText(_translate("MainWindow", "Add your past paper by clicking \"Load Past Paper\" "))
        self.label_pastPaperFileName.setText(_translate("MainWindow", ""))
        self.btn_loadPastPaper.setText(_translate("MainWindow", "Load Past Paper"))
        self.label_loadMemoInstruction.setText(_translate("MainWindow", "Add the memo to your past paper by clicking \"Load Past Paper Memo\" "))
        self.label_memoFileName.setText(_translate("MainWindow", ""))
        self.btn_loadMemo.setText(_translate("MainWindow", "Load Past Paper Memo"))
        self.label_generateInstruction.setText(_translate("MainWindow", "Once both documents are loaded, click \"Generate Layout\" to go to the marking window. "))
        self.btn_generateLayout.setText(_translate("MainWindow", "Generate Layout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
