# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question_answer_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuestionAnswerViewer(object):
    def setupUi(self, QuestionAnswerViewer):
        QuestionAnswerViewer.setObjectName("QuestionAnswerViewer")
        QuestionAnswerViewer.resize(1060, 738)
        self.verticalLayoutWidget = QtWidgets.QWidget(QuestionAnswerViewer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 381, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.layout_questionTitle = QtWidgets.QVBoxLayout()
        self.layout_questionTitle.setObjectName("layout_questionTitle")
        self.questionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.questionLabel.setObjectName("questionLabel")
        self.layout_questionTitle.addWidget(self.questionLabel)
        self.stemImageLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.stemImageLabel.setObjectName("stemImageLabel")
        self.layout_questionTitle.addWidget(self.stemImageLabel)
        self.questionImageLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.questionImageLabel.setObjectName("questionImageLabel")
        self.layout_questionTitle.addWidget(self.questionImageLabel)
        self.layout_toolButtons = QtWidgets.QHBoxLayout()
        self.layout_toolButtons.setObjectName("layout_toolButtons")
        self.prevToolButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.prevToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.prevToolButton.setObjectName("prevToolButton")
        self.layout_toolButtons.addWidget(self.prevToolButton)
        self.nextToolButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.nextToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.nextToolButton.setObjectName("nextToolButton")
        self.layout_toolButtons.addWidget(self.nextToolButton)
        self.layout_questionTitle.addLayout(self.layout_toolButtons)
        self.mainLayout.addLayout(self.layout_questionTitle)
        self.answerImageLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.answerImageLabel.setObjectName("answerImageLabel")
        self.mainLayout.addWidget(self.answerImageLabel)

        self.retranslateUi(QuestionAnswerViewer)
        QtCore.QMetaObject.connectSlotsByName(QuestionAnswerViewer)

    def retranslateUi(self, QuestionAnswerViewer):
        _translate = QtCore.QCoreApplication.translate
        QuestionAnswerViewer.setWindowTitle(_translate("QuestionAnswerViewer", "Dialog"))
        self.questionLabel.setText(_translate("QuestionAnswerViewer", "Question:"))
        self.stemImageLabel.setText(_translate("QuestionAnswerViewer", "TextLabel"))
        self.questionImageLabel.setText(_translate("QuestionAnswerViewer", "TextLabel"))
        self.prevToolButton.setText(_translate("QuestionAnswerViewer", "<"))
        self.nextToolButton.setText(_translate("QuestionAnswerViewer", ">"))
        self.answerImageLabel.setText(_translate("QuestionAnswerViewer", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuestionAnswerViewer = QtWidgets.QDialog()
    ui = Ui_QuestionAnswerViewer()
    ui.setupUi(QuestionAnswerViewer)
    QuestionAnswerViewer.show()
    sys.exit(app.exec_())
