# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question_answer_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuestionAnswerViewer(object):
    def setupUi(self, QuestionAnswerViewer):
        QuestionAnswerViewer.setObjectName("QuestionAnswerViewer")
        QuestionAnswerViewer.resize(1060, 738)

        self.retranslateUi(QuestionAnswerViewer)
        QtCore.QMetaObject.connectSlotsByName(QuestionAnswerViewer)

    def retranslateUi(self, QuestionAnswerViewer):
        _translate = QtCore.QCoreApplication.translate
        QuestionAnswerViewer.setWindowTitle(_translate("QuestionAnswerViewer", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuestionAnswerViewer = QtWidgets.QDialog()
    ui = Ui_QuestionAnswerViewer()
    ui.setupUi(QuestionAnswerViewer)
    QuestionAnswerViewer.show()
    sys.exit(app.exec_())
